using System;

namespace LeanCloud.Realtime
{
	public class AVIMException : Exception
	{
		public enum ErrorCode
		{
			OtherCause = -1,
			FromServer = 4000,
			UnknownError = 1006,
			APP_NOT_AVAILABLE = 4100,
			SIGNATURE_FAILED = 4102,
			INVALID_LOGIN = 4103,
			SESSION_REQUIRED = 4105,
			READ_TIMEOUT = 4107,
			LOGIN_TIMEOUT = 4108,
			FRAME_TOO_LONG = 4109,
			INVALID_ORIGIN = 4110,
			SESSION_CONFLICT = 4111,
			APP_QUOTA_EXCEEDED = 4113,
			UNPARSEABLE_RAW_MESSAGE = 4114,
			KICKED_BY_APP = 4115,
			MESSAGE_SENT_QUOTA_EXCEEDED = 4116,
			INTERNAL_ERROR = 4200,
			SEND_MESSAGE_TIMEOUT = 4201,
			CONVERSATION_API_FAILED = 4301,
			CONVERSATION_SIGNATURE_FAILED = 4302,
			CONVERSATION_NOT_FOUND = 4303,
			CONVERSATION_FULL = 4304,
			CONVERSATION_REJECTED_BY_APP = 4305,
			CONVERSATION_UPDATE_FAILED = 4306,
			CONVERSATION_READ_ONLY = 4307,
			CONVERSATION_NOT_ALLOWED = 4308,
			CONVERSATION_UPDATE_REJECT = 4309,
			CONVERSATION_QUERY_FAILED = 4310,
			CONVERSATION_LOG_FAILED = 4311,
			CONVERSATION_LOG_REJECT = 4312,
			SYSTEM_CONVERSATION_REQUIRED = 4313,
			NORMAL_CONVERSATION_REQUIRED = 4314,
			CONVERSATION_BLACKLISTED = 4315,
			TRANSIENT_CONVERSATION_REQUIRED = 4316,
			INVALID_MESSAGING_TARGET = 4401,
			MESSAGE_REJECTED_BY_APP = 4402,
			CAN_NOT_EXCUTE_COMMAND = 1002
		}

		public int AppCode { get; private set; }

		public ErrorCode Code { get; private set; }

		internal AVIMException(ErrorCode code, string message, Exception cause = null)
		{
		}

		internal AVIMException(int code, int appCode, string message, Exception cause = null)
		{
		}
	}
}
